export const ALL_PRODUCT_REQUEST = 'ALL_PRODUCT_REQUEST'
export const ALL_PRODUCT_SUCCESS = 'ALL_PRODUCT_SUCCESS'
export const ALL_PRODUCT_FAILIURE = 'ALL_PRODUCT_FAILIURE'

export const SINGLE_PRODUCT_REQUEST = 'SINGLE_PRODUCT_REQUEST'
export const SINGLE_PRODUCT_SUCCESS = 'SINGLE_PRODUCT_SUCCESS'
export const SINGLE_PRODUCT_FAILIURE = 'SINGLE_PRODUCT_FAILIURE'


export const CLEAR_ERRORS = 'CLEAR_ERRORS'
